version : '3.8'
services:
  app:
    build:
      context: ./backend
    volumes:
      - .:/srv/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    